version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint

  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - persist_to_workspace:
          root: workspace
          paths: build

  deploy:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: workspace
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run deploy

            

workflows:
  build-and-deploy:
    jobs:
      - lint
      - build
      - deploy:
          requires:
            - lint
            - build
