version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint

  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: npm run deploy
            - run: npm run invalidate

workflows:
  lint-build-deploy:
    jobs:
      - lint
      - build-and-deploy:
          requires:
            - lint
